export const services = [
    {
        slug: "warehousing-storage",
        title: "Warehousing & Storage",
        eyebrow: "Inventory control",
        description: "Secure storage space for fast-moving, seasonal, and overflow inventory with organized stock handling.",
        image: "/assets/imgs/page/homepage1/banner-storage-unsplash.jpg",
        icon: "warehouse",
        overview: "Go Connect Hub gives ecommerce teams a clean storage operation with structured receiving, organized locations, and stock visibility built around day-to-day fulfilment speed.",
        bestFor: "Amazon sellers, Shopify brands, TikTok shops, wholesale teams, and growing stores that need dependable storage without warehouse overhead.",
        includes: [
            "Short-term and long-term inventory storage",
            "SKU-level organization and stock handling",
            "Seasonal, overflow, and fast-moving product support",
            "Receiving checks before inventory is placed into storage",
        ],
        process: [
            "Inventory arrives at our fulfilment facility.",
            "Items are checked, counted, and organized by SKU.",
            "Stock is stored for quick picking and dispatch.",
        ],
    },
    {
        slug: "pick-pack-fulfilment",
        title: "Pick & Pack Fulfilment",
        eyebrow: "Daily dispatch",
        description: "Accurate order picking, packing, and dispatch workflows designed for smooth day-to-day ecommerce operations.",
        image: "/assets/imgs/page/homepage1/warehouse.png",
        icon: "box",
        overview: "Our pick and pack fulfilment keeps orders moving with clear workflows, careful packing standards, and carrier-ready dispatch handling.",
        bestFor: "Brands that need reliable daily order fulfilment for marketplace, DTC, and social commerce sales channels.",
        includes: [
            "Order picking from organized inventory",
            "Packing aligned with product and channel needs",
            "Dispatch preparation for courier collection",
            "Quality checks before orders leave the warehouse",
        ],
        process: [
            "Orders are received and matched to available stock.",
            "Items are picked, checked, and packed.",
            "Finished parcels are prepared for outbound dispatch.",
        ],
    },
    {
        slug: "fba-fbm-fulfilment",
        title: "FBA & FBM Fulfilment",
        eyebrow: "Amazon ready",
        description: "Amazon-ready fulfilment support for both FBA prep requirements and FBM order processing across channels.",
        image: "/assets/imgs/page/homepage1/cargo-ship.png",
        icon: "amazon",
        overview: "Go Connect Hub supports Amazon sellers with both FBA prep and FBM fulfilment, helping inventory meet platform requirements and customer delivery expectations.",
        bestFor: "Amazon sellers that need prep, labelling, packing, dispatch, and returns support from one fulfilment partner.",
        includes: [
            "FBA prep support for inbound Amazon inventory",
            "FBM order handling and dispatch preparation",
            "Labelling and packaging support",
            "Inventory movement between storage and order fulfilment",
        ],
        process: [
            "Inventory is received and checked against requirements.",
            "Products are prepped, labelled, or packed as needed.",
            "Orders or inbound shipments are dispatched through the right workflow.",
        ],
    },
    {
        slug: "kitting-bundling",
        title: "Kitting & Bundling",
        eyebrow: "Product assembly",
        description: "Assemble multi-item bundles, promotional kits, and custom product sets with consistent packing standards.",
        image: "/assets/imgs/page/homepage1/img2.png",
        icon: "bundle",
        overview: "We turn individual SKUs into ready-to-sell kits, bundles, launch packs, and promotional sets with consistent assembly and quality checks.",
        bestFor: "Brands running campaigns, subscription boxes, product launches, multi-item offers, or marketplace bundles.",
        includes: [
            "Multi-SKU bundle assembly",
            "Promotional kit preparation",
            "Custom packing instructions",
            "Final bundle checks before storage or dispatch",
        ],
        process: [
            "Components are received and organized.",
            "Bundles are assembled to your instructions.",
            "Finished kits are checked, labelled, and prepared for fulfilment.",
        ],
    },
    {
        slug: "repackaging-relabelling",
        title: "Repackaging & Relabelling",
        eyebrow: "Compliance support",
        description: "Update labels, barcodes, and packaging formats to meet platform, retail, or customer-specific requirements.",
        image: "/assets/imgs/page/homepage1/img3.png",
        icon: "label",
        overview: "When products need updated packaging, corrected labels, or marketplace-ready barcode work, Go Connect Hub handles the operational detail before items move forward.",
        bestFor: "Sellers that need barcode updates, retail packaging changes, Amazon prep corrections, or cleaner customer presentation.",
        includes: [
            "Barcode and label application",
            "Packaging refresh or replacement",
            "Platform-specific prep support",
            "Sorting and checking before restocking or dispatch",
        ],
        process: [
            "Products are reviewed against the required packaging instruction.",
            "Labels or packaging are updated in a controlled workflow.",
            "Finished units are checked and moved to storage or dispatch.",
        ],
    },
    {
        slug: "wholesale-b2b-fulfilment",
        title: "Wholesale (B2B) Fulfilment",
        eyebrow: "Bulk orders",
        description: "Manage carton, pallet, and bulk order fulfilment for wholesale accounts with structured outbound handling.",
        image: "/assets/imgs/page/services/warehouse.png",
        icon: "wholesale",
        overview: "Our B2B fulfilment support helps brands move larger wholesale orders with carton, pallet, and account-specific handling requirements.",
        bestFor: "Growing ecommerce brands supplying retailers, distributors, wholesale buyers, and multi-location partners.",
        includes: [
            "Carton and pallet order preparation",
            "Bulk picking and outbound handling",
            "Account-specific packing instructions",
            "Dispatch coordination for larger shipments",
        ],
        process: [
            "Wholesale order requirements are reviewed.",
            "Stock is picked and prepared in cartons or pallets.",
            "Outbound goods are staged for collection or delivery.",
        ],
    },
    {
        slug: "cross-docking-service",
        title: "Cross Docking Service",
        eyebrow: "Fast transfer",
        description: "Move inbound inventory quickly through the warehouse with minimal storage time and faster outbound turnaround.",
        image: "/assets/imgs/page/services/train.png",
        icon: "transfer",
        overview: "Cross docking helps stock move from inbound receiving to outbound dispatch quickly, reducing storage time and speeding up delivery flow.",
        bestFor: "Businesses that need fast inventory transfer, urgent campaign stock movement, or efficient inbound-to-outbound routing.",
        includes: [
            "Inbound unloading and receiving checks",
            "Sorting by destination or order requirement",
            "Short-hold staging for outbound dispatch",
            "Reduced storage dependency for fast-moving stock",
        ],
        process: [
            "Inbound goods arrive and are checked.",
            "Stock is sorted for outbound movement.",
            "Items are staged and moved onward with minimal delay.",
        ],
    },
    {
        slug: "return-handling",
        title: "Return Handling",
        eyebrow: "Reverse logistics",
        description: "Process customer returns efficiently with checking, sorting, restocking, and reporting support.",
        image: "/assets/imgs/page/homepage1/bg-contact.png",
        icon: "returns",
        overview: "Go Connect Hub keeps returns organized with inspection, sorting, restocking support, and clear handling so returned inventory can be recovered faster.",
        bestFor: "Marketplace sellers and ecommerce brands that need dependable reverse logistics without slowing daily fulfilment.",
        includes: [
            "Returned item receiving",
            "Condition checking and sorting",
            "Restocking support for sellable inventory",
            "Clear handling for damaged or exception items",
        ],
        process: [
            "Returns arrive and are matched to handling requirements.",
            "Items are inspected, sorted, and recorded.",
            "Sellable stock is prepared for restocking.",
        ],
    },
    {
        slug: "container-unloading",
        title: "Container Unloading",
        eyebrow: "Inbound intake",
        description: "Unload containers safely and efficiently to speed up receiving, inventory intake, and warehouse flow.",
        image: "/assets/imgs/page/homepage1/banner-containers-unsplash.jpg",
        icon: "container",
        overview: "Our container unloading service helps inbound stock enter the fulfilment workflow quickly, with safer handling and organized intake from the first touch.",
        bestFor: "Importers, marketplace sellers, and scaling brands receiving larger inbound shipments or seasonal stock.",
        includes: [
            "Container unloading support",
            "Pallet, carton, and loose-load handling",
            "Initial receiving checks",
            "Movement into storage, prep, or cross docking workflows",
        ],
        process: [
            "The container arrives at the receiving point.",
            "Goods are unloaded and checked for intake.",
            "Inventory moves into storage, prep, or onward dispatch.",
        ],
    },
];

export const featuredServices = services.slice(0, 6);

export function getServiceBySlug(slug) {
    return services.find((service) => service.slug === slug);
}
