export const services = [
    {
        slug: "warehousing-storage",
        title: "Warehousing & Storage",
        eyebrow: "Inventory control",
        description: "Secure storage space for fast-moving, seasonal, and overflow inventory with organized stock handling.",
        image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
        icon: "warehouse",
        overview: "Go Connect Hub gives ecommerce teams a clean storage operation with structured receiving, organized locations, and stock visibility built around day-to-day fulfilment speed.",
        bestFor: "Amazon sellers, Shopify brands, TikTok shops, wholesale teams, and growing stores that need dependable storage without warehouse overhead.",
        includes: [
            "Short-term and long-term inventory storage",
            "SKU-level organization and stock handling",
            "Seasonal, overflow, and fast-moving product support",
            "Receiving checks before inventory is placed into storage",
        ],
        process: [
            { title: "Inventory Arrives", desc: "Your inventory arrives at our fulfilment facility and is logged in." },
            { title: "Check & Organize", desc: "Items are checked, counted, and organized by SKU and location." },
            { title: "Stored & Ready", desc: "Stock is stored and ready for fast picking and dispatch." },
        ],
        stats: [
            { value: "Same Day", label: "Receiving turnaround" },
            { value: "SKU-Level", label: "Stock organization" },
            { value: "Flexible", label: "Short & long-term storage" },
        ],
    },
    {
        slug: "pick-pack-fulfilment",
        title: "Pick & Pack Fulfilment",
        eyebrow: "Daily dispatch",
        description: "Accurate order picking, packing, and dispatch workflows designed for smooth day-to-day ecommerce operations.",
        image: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1400&q=80",
        icon: "box",
        overview: "Our pick and pack fulfilment keeps orders moving with clear workflows, careful packing standards, and carrier-ready dispatch handling.",
        bestFor: "Brands that need reliable daily order fulfilment for marketplace, DTC, and social commerce sales channels.",
        includes: [
            "Order picking from organized inventory",
            "Packing aligned with product and channel needs",
            "Dispatch preparation for courier collection",
            "Quality checks before orders leave the warehouse",
        ],
        process: [
            { title: "Order Received", desc: "Orders are received and matched to available stock in the system." },
            { title: "Pick & Pack", desc: "Items are picked, checked, and carefully packed to standard." },
            { title: "Dispatched", desc: "Finished parcels are prepared and staged for outbound dispatch." },
        ],
        stats: [
            { value: "99%+", label: "Pick accuracy rate" },
            { value: "Daily", label: "Dispatch cut-offs" },
            { value: "Multi-channel", label: "Platform support" },
        ],
    },
    {
        slug: "fba-fbm-fulfilment",
        title: "FBA & FBM Fulfilment",
        eyebrow: "Amazon ready",
        description: "Amazon-ready fulfilment support for both FBA prep requirements and FBM order processing across channels.",
        image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1400&q=80",
        icon: "amazon",
        overview: "Go Connect Hub supports Amazon sellers with both FBA prep and FBM fulfilment, helping inventory meet platform requirements and customer delivery expectations.",
        bestFor: "Amazon sellers that need prep, labelling, packing, dispatch, and returns support from one fulfilment partner.",
        includes: [
            "FBA prep support for inbound Amazon inventory",
            "FBM order handling and dispatch preparation",
            "Labelling and packaging support",
            "Inventory movement between storage and order fulfilment",
        ],
        process: [
            { title: "Inventory Checked", desc: "Inventory is received and checked against Amazon requirements." },
            { title: "Prep & Label", desc: "Products are prepped, labelled, or packed to platform spec." },
            { title: "Dispatched", desc: "Orders or inbound shipments are dispatched through the right workflow." },
        ],
        stats: [
            { value: "FBA + FBM", label: "Both channels covered" },
            { value: "Compliant", label: "Amazon prep standards" },
            { value: "Fast", label: "Inbound turnaround" },
        ],
    },
    {
        slug: "kitting-bundling",
        title: "Kitting & Bundling",
        eyebrow: "Product assembly",
        description: "Assemble multi-item bundles, promotional kits, and custom product sets with consistent packing standards.",
        image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1400&q=80",
        icon: "bundle",
        overview: "We turn individual SKUs into ready-to-sell kits, bundles, launch packs, and promotional sets with consistent assembly and quality checks.",
        bestFor: "Brands running campaigns, subscription boxes, product launches, multi-item offers, or marketplace bundles.",
        includes: [
            "Multi-SKU bundle assembly",
            "Promotional kit preparation",
            "Custom packing instructions",
            "Final bundle checks before storage or dispatch",
        ],
        process: [
            { title: "Components Received", desc: "Individual components are received and organized by instruction." },
            { title: "Assembly", desc: "Bundles are assembled accurately to your specification." },
            { title: "Checked & Ready", desc: "Finished kits are quality-checked, labelled, and prepared for fulfilment." },
        ],
        stats: [
            { value: "Custom", label: "Bundle instructions" },
            { value: "QC Checked", label: "Every kit inspected" },
            { value: "Launch Ready", label: "Campaign support" },
        ],
    },
    {
        slug: "repackaging-relabelling",
        title: "Repackaging & Relabelling",
        eyebrow: "Compliance support",
        description: "Update labels, barcodes, and packaging formats to meet platform, retail, or customer-specific requirements.",
        image: "https://images.unsplash.com/photo-1565536421961-68b76e6f62d1?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1565536421961-68b76e6f62d1?auto=format&fit=crop&w=1400&q=80",
        icon: "label",
        overview: "When products need updated packaging, corrected labels, or marketplace-ready barcode work, Go Connect Hub handles the operational detail before items move forward.",
        bestFor: "Sellers that need barcode updates, retail packaging changes, Amazon prep corrections, or cleaner customer presentation.",
        includes: [
            "Barcode and label application",
            "Packaging refresh or replacement",
            "Platform-specific prep support",
            "Sorting and checking before restocking or dispatch",
        ],
        process: [
            { title: "Review Requirements", desc: "Products are reviewed against the required packaging instruction." },
            { title: "Update Labels", desc: "Labels or packaging are updated in a controlled workflow." },
            { title: "Restock or Dispatch", desc: "Finished units are checked and moved to storage or dispatch." },
        ],
        stats: [
            { value: "Accurate", label: "Label application" },
            { value: "Platform", label: "Compliant packaging" },
            { value: "Fast", label: "Turnaround time" },
        ],
    },
    {
        slug: "wholesale-b2b-fulfilment",
        title: "Wholesale (B2B) Fulfilment",
        eyebrow: "Bulk orders",
        description: "Manage carton, pallet, and bulk order fulfilment for wholesale accounts with structured outbound handling.",
        image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1400&q=80",
        icon: "wholesale",
        overview: "Our B2B fulfilment support helps brands move larger wholesale orders with carton, pallet, and account-specific handling requirements.",
        bestFor: "Growing ecommerce brands supplying retailers, distributors, wholesale buyers, and multi-location partners.",
        includes: [
            "Carton and pallet order preparation",
            "Bulk picking and outbound handling",
            "Account-specific packing instructions",
            "Dispatch coordination for larger shipments",
        ],
        process: [
            { title: "Order Review", desc: "Wholesale order requirements and packing instructions are reviewed." },
            { title: "Pick & Prepare", desc: "Stock is picked and prepared in cartons or pallets to spec." },
            { title: "Staged for Dispatch", desc: "Outbound goods are staged and coordinated for collection or delivery." },
        ],
        stats: [
            { value: "Pallet", label: "& carton ready" },
            { value: "B2B", label: "Account-specific" },
            { value: "Bulk", label: "Volume handling" },
        ],
    },
    {
        slug: "cross-docking-service",
        title: "Cross Docking Service",
        eyebrow: "Fast transfer",
        description: "Move inbound inventory quickly through the warehouse with minimal storage time and faster outbound turnaround.",
        image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1400&q=80",
        icon: "transfer",
        overview: "Cross docking helps stock move from inbound receiving to outbound dispatch quickly, reducing storage time and speeding up delivery flow.",
        bestFor: "Businesses that need fast inventory transfer, urgent campaign stock movement, or efficient inbound-to-outbound routing.",
        includes: [
            "Inbound unloading and receiving checks",
            "Sorting by destination or order requirement",
            "Short-hold staging for outbound dispatch",
            "Reduced storage dependency for fast-moving stock",
        ],
        process: [
            { title: "Inbound Arrives", desc: "Inbound goods arrive at the receiving point and are checked." },
            { title: "Sort & Stage", desc: "Stock is sorted by destination or order and staged for outbound." },
            { title: "Fast Dispatch", desc: "Items are moved onward with minimal delay and no storage overhead." },
        ],
        stats: [
            { value: "Minimal", label: "Storage time" },
            { value: "Same Day", label: "Outbound staging" },
            { value: "Efficient", label: "Inbound-to-outbound" },
        ],
    },
    {
        slug: "return-handling",
        title: "Return Handling",
        eyebrow: "Reverse logistics",
        description: "Process customer returns efficiently with checking, sorting, restocking, and reporting support.",
        image: "https://images.unsplash.com/photo-1612599539537-2788b23434a0?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1612599539537-2788b23434a0?auto=format&fit=crop&w=1400&q=80",
        icon: "returns",
        overview: "Go Connect Hub keeps returns organized with inspection, sorting, restocking support, and clear handling so returned inventory can be recovered faster.",
        bestFor: "Marketplace sellers and ecommerce brands that need dependable reverse logistics without slowing daily fulfilment.",
        includes: [
            "Returned item receiving",
            "Condition checking and sorting",
            "Restocking support for sellable inventory",
            "Clear handling for damaged or exception items",
        ],
        process: [
            { title: "Returns Arrive", desc: "Returns arrive and are matched to handling requirements." },
            { title: "Inspect & Sort", desc: "Items are inspected, sorted, and recorded accurately." },
            { title: "Restock", desc: "Sellable stock is prepared and moved back for restocking." },
        ],
        stats: [
            { value: "Fast", label: "Returns processing" },
            { value: "Sorted", label: "Condition grading" },
            { value: "Recovery", label: "Sellable stock first" },
        ],
    },
    {
        slug: "container-unloading",
        title: "Container Unloading",
        eyebrow: "Inbound intake",
        description: "Unload containers safely and efficiently to speed up receiving, inventory intake, and warehouse flow.",
        image: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?auto=format&fit=crop&w=1400&q=80",
        heroImage: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?auto=format&fit=crop&w=1400&q=80",
        icon: "container",
        overview: "Our container unloading service helps inbound stock enter the fulfilment workflow quickly, with safer handling and organized intake from the first touch.",
        bestFor: "Importers, marketplace sellers, and scaling brands receiving larger inbound shipments or seasonal stock.",
        includes: [
            "Container unloading support",
            "Pallet, carton, and loose-load handling",
            "Initial receiving checks",
            "Movement into storage, prep, or cross docking workflows",
        ],
        process: [
            { title: "Container Arrives", desc: "The container arrives at the receiving point and is booked in." },
            { title: "Unload & Check", desc: "Goods are unloaded safely and checked for intake." },
            { title: "Into Workflow", desc: "Inventory moves into storage, prep, or onward dispatch." },
        ],
        stats: [
            { value: "Safe", label: "Unloading process" },
            { value: "Checked", label: "Every item received" },
            { value: "Seamless", label: "Into fulfilment flow" },
        ],
    },
];

export const featuredServices = services.slice(0, 6);

export function getServiceBySlug(slug) {
    return services.find((service) => service.slug === slug);
}
